language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

branches:
  only:
    - master 

install:
  - sudo apt-get install gdal-bin
  - sudo pip install -e . --use-mirrors
  - sudo pip install pep8

script:
  - pep8 .
  - python manage.py validate
